# Funding links for the "Sponsor" button on GitHub
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [ariellewolter]
ko_fi: ariellewolter
